# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-bD1B37KyZFK8AAxKdnPP8NDafsSokp
"""

import pandas as pd

df = pd.read_csv('sales_data.csv', header = 0, index_col=False)
df.head(20)

df.dropna(subset=['Order ID', 'Product'], inplace=True)
df.head(15)

df['Price Each'] = df['Price Each'].fillna(
    df.groupby('Product')['Price Each'].transform('mean')
)
df

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y', errors='coerce')
df['Order Date'].dtype

df['Total_Sales'] = df['Quantity Ordered'] * df['Price Each']
df.head(11)

df_grouped = df.groupby(df['Order Date'].dt.strftime('%b'))['Total_Sales'].sum()
df_grouped.head(5)

df_grouped_qty = df.groupby([df['Order Date'].dt.strftime('%Y-%m'),df['Product']])['Quantity Ordered'].sum()
df_grouped_qty.head(12)

max_products_per_month = df_grouped_qty.groupby(level=0).idxmax()
max_products_per_month

print("--------MONTHLY REPORT-------------")
print(df_grouped)
print("--------BEST SELLING PRODUCT PER MONTH-------------")
print(max_products_per_month)

df.to_csv('cleaned_sales.csv')